# Shell function library for nix-to-deb build phase
#
# Exports mkShellHelpers — takes resolved config, returns a bash string
# defining all shell functions used in the installPhase pipeline.
#
# Fixes:
#   #1 — resolve_binary: consistent binary resolution
#   #2 — collect_elf_closure: empty excludeLibs no longer drops all libs
#   #3 — collect_elf_closure: patchelf-based instead of ldd scraping
#   #6 — verify_package_tree: detects leftover /nix/store references
#   #7 — copy_private_libs: collision detection
#   #8 — copy_private_libs: preserves symlink chains
{ lib, pkgs }:

{
  mkShellHelpers =
    {
      pname,
      binName,
      package,
      realBinary ? null,
      bundlePath,
      systemLibDir,
      interpreter,
      excludeLibs ? [ "glibc" ],
      extraLibs ? [ ],
      extraLibPackages ? [ ],
      createCompatSymlinks ? false,
      targetGlibcBaseline ? null,
      allowedSystemLibs ? [
        "libm.so"
        "libc.so"
        "libdl.so"
        "librt.so"
        "libpthread.so"
        "libutil.so"
        "libcrypt.so"
        "libresolv.so"
        "libnss_dns.so"
        "libnss_files.so"
        "libgcc_s.so"
        "libstdc++.so"
        "ld-linux-x86-64.so"
        "ld-linux-aarch64.so"
        "linux-vdso.so"
      ],
    }:
    let
      excludePattern = if excludeLibs == [ ] then "" else builtins.concatStringsSep "\\|" excludeLibs;

      hasExcludes = excludeLibs != [ ];
    in
    ''
      # ==============================================================
      # Shell helpers generated by nix-to-deb
      # ==============================================================

      # Global state
      RESOLVED_BINARY=""
      declare -A _ELF_CLOSURE_VISITED
      declare -a _ELF_CLOSURE_LIBS
      declare -A _CLOSURE_PKG_DIRS
      declare -A _BUNDLED_LIB_SOURCES
      COMPUTED_GLIBC_FLOOR=""
      COMPUTED_GLIBC_MAX_TAG=""
      COMPUTED_GLIBC_SOURCE=""
      TARGET_GLIBC_BASELINE="${if targetGlibcBaseline != null then targetGlibcBaseline else ""}"

      # --- resolve_binary (#1) ---
      # Determines the real binary path. If realBinary was specified, uses it.
      # Otherwise checks .${binName}-wrapped first, then ${binName}.
      # Fails early if the binary doesn't exist.
      resolve_binary() {
        ${
          if realBinary != null then
            ''
              if [ -f "${realBinary}" ]; then
                RESOLVED_BINARY="${realBinary}"
              else
                echo "ERROR: specified realBinary '${realBinary}' does not exist" >&2
                exit 1
              fi
            ''
          else
            ''
              if [ -f "${package}/bin/.${binName}-wrapped" ]; then
                RESOLVED_BINARY="${package}/bin/.${binName}-wrapped"
              elif [ -f "${package}/bin/${binName}" ]; then
                RESOLVED_BINARY="${package}/bin/${binName}"
              else
                echo "ERROR: could not find binary '${binName}' in ${package}/bin/" >&2
                echo "  Tried: .${binName}-wrapped, ${binName}" >&2
                exit 1
              fi
            ''
        }
        echo "==> Resolved binary: $RESOLVED_BINARY"
      }

      _register_pkg_root() {
        local path="$1"
        local pkg_root=""
        case "$path" in
          /nix/store/*)
            pkg_root=$(echo "$path" | sed 's|^\(/nix/store/[^/]*\).*|\1|')
            [ -n "$pkg_root" ] && _CLOSURE_PKG_DIRS["$pkg_root"]=1
            ;;
        esac
      }

      _record_bundled_lib_source() {
        local bundled_name="$1"
        local source_path="$2"
        [ -n "$bundled_name" ] || return 0
        [ -n "$source_path" ] || return 0
        if [ -z "''${_BUNDLED_LIB_SOURCES[$bundled_name]+x}" ]; then
          _BUNDLED_LIB_SOURCES["$bundled_name"]="$source_path"
        fi
      }

      _record_bundled_lib_alias() {
        local alias_name="$1"
        local target_name="$2"
        [ -n "$alias_name" ] || return 0
        [ -n "$target_name" ] || return 0
        if [ -z "''${_BUNDLED_LIB_SOURCES[$alias_name]+x}" ] && [ -n "''${_BUNDLED_LIB_SOURCES[$target_name]+x}" ]; then
          _BUNDLED_LIB_SOURCES["$alias_name"]="''${_BUNDLED_LIB_SOURCES[$target_name]}"
        fi
      }

      _version_gt() {
        local lhs="$1" rhs="$2"
        [ "$lhs" != "$rhs" ] && [ "$(printf '%s\n%s\n' "$lhs" "$rhs" | sort -V | tail -n1)" = "$lhs" ]
      }

      compute_glibc_floor() {
        echo "==> Computing GLIBC floor from staged ELF payload..."
        COMPUTED_GLIBC_FLOOR=""
        COMPUTED_GLIBC_MAX_TAG=""
        COMPUTED_GLIBC_SOURCE=""

        while IFS= read -r -d "" staged_file; do
          if ! file -b "$staged_file" | grep -q "ELF"; then
            continue
          fi

          local file_max_tag=""
          file_max_tag=$(readelf --version-info "$staged_file" 2>/dev/null \
            | grep -o 'GLIBC_[0-9][0-9.]*' \
            | sort -uV \
            | tail -n1) || true

          if [ -z "$file_max_tag" ]; then
            continue
          fi

          if [ -z "$COMPUTED_GLIBC_MAX_TAG" ] || _version_gt "''${file_max_tag#GLIBC_}" "''${COMPUTED_GLIBC_MAX_TAG#GLIBC_}"; then
            COMPUTED_GLIBC_MAX_TAG="$file_max_tag"
            COMPUTED_GLIBC_FLOOR="''${file_max_tag#GLIBC_}"
            COMPUTED_GLIBC_SOURCE="$staged_file"
          fi
        done < <(find "$PKG" -type f -print0)

        if [ -z "$COMPUTED_GLIBC_FLOOR" ] && [ -n "$TARGET_GLIBC_BASELINE" ]; then
          COMPUTED_GLIBC_FLOOR="$TARGET_GLIBC_BASELINE"
          echo "  WARN: no GLIBC_* tags found in staged ELF payload; falling back to target baseline $TARGET_GLIBC_BASELINE" >&2
        fi

        if [ -n "$COMPUTED_GLIBC_FLOOR" ]; then
          echo "==> GLIBC floor: libc6 (>= $COMPUTED_GLIBC_FLOOR)"
        fi

        if [ -n "$TARGET_GLIBC_BASELINE" ] && [ -n "$COMPUTED_GLIBC_FLOOR" ] && _version_gt "$COMPUTED_GLIBC_FLOOR" "$TARGET_GLIBC_BASELINE"; then
          echo "  WARN: computed GLIBC floor $COMPUTED_GLIBC_FLOOR exceeds target baseline $TARGET_GLIBC_BASELINE" >&2
          if [ -n "$COMPUTED_GLIBC_SOURCE" ]; then
            echo "    Highest requirement seen in: $COMPUTED_GLIBC_SOURCE ($COMPUTED_GLIBC_MAX_TAG)" >&2
          fi
        fi
      }

      # --- collect_elf_closure (#3, #2) ---
      # Deterministic ELF closure walker using patchelf instead of ldd.
      # Resolves DT_NEEDED entries against RPATH dirs.
      # When excludeLibs is empty, no filtering is applied (#2).
      collect_elf_closure() {
        local root_file="$1"
        local real_root
        real_root=$(readlink -f "$root_file" 2>/dev/null) || real_root="$root_file"
        _register_pkg_root "$real_root"
        _ELF_CLOSURE_VISITED=()
        _ELF_CLOSURE_LIBS=()
        _walk_elf_deps "$real_root"
      }

      _walk_elf_deps() {
        local file="$1"
        local real_file

        # Resolve symlinks to canonical path
        real_file=$(readlink -f "$file" 2>/dev/null) || real_file="$file"

        # Skip if already visited
        [ -n "''${_ELF_CLOSURE_VISITED[$real_file]+x}" ] && return
        _ELF_CLOSURE_VISITED["$real_file"]=1

        # Get DT_NEEDED entries
        local needed
        needed=$(patchelf --print-needed "$real_file" 2>/dev/null) || return 0

        # Get RPATH search dirs
        local rpath
        rpath=$(patchelf --print-rpath "$real_file" 2>/dev/null) || rpath=""

        # Build array of search dirs from RPATH
        local -a search_dirs
        IFS=':' read -ra search_dirs <<< "$rpath"

        for lib_name in $needed; do
          local found=""

          # Handle absolute-path DT_NEEDED entries (nix often uses these)
          if [[ "$lib_name" == /* ]]; then
            if [ -f "$lib_name" ]; then
              found="$lib_name"
            else
              echo "  NOTE: absolute DT_NEEDED path does not exist: $lib_name (from $real_file)" >&2
              continue
            fi
          fi

          # Search in RPATH dirs (only for soname-style entries)
          if [ -z "$found" ]; then
            for dir in "''${search_dirs[@]}"; do
              # Expand $ORIGIN if present
              local expanded_dir
              expanded_dir="''${dir/\$ORIGIN/$(dirname "$real_file")}"
              if [ -f "$expanded_dir/$lib_name" ]; then
                found="$expanded_dir/$lib_name"
                break
              fi
            done
          fi

          # Not found in RPATH — check if it's an allowed system lib
          if [ -z "$found" ]; then
            local is_allowed=false
            for allowed in ${builtins.concatStringsSep " " (map (l: ''"${l}"'') allowedSystemLibs)}; do
              case "$lib_name" in
                "$allowed"*) is_allowed=true; break ;;
              esac
            done
            if $is_allowed; then
              continue
            fi
            # Not allowed and not found — note it and move on
            echo "  NOTE: unresolved DT_NEEDED: $lib_name (from $real_file)" >&2
            continue
          fi

          # Apply exclude filter only if we have excludes (#2)
          ${
            if hasExcludes then
              ''
                if echo "$found" | grep -q '${excludePattern}'; then
                  continue
                fi
              ''
            else
              "# No excludeLibs — bundling all resolved libs"
          }

          # Skip if not from nix store
          case "$found" in
            /nix/store/*) ;;
            *) continue ;;
          esac

          _ELF_CLOSURE_LIBS+=("$found")
          _register_pkg_root "$found"
          # Recurse into this lib's deps
          _walk_elf_deps "$found"
        done
      }

      # Helper: copy closure libs accumulated in _ELF_CLOSURE_LIBS
      copy_closure_libs() {
        for lib_path in "''${_ELF_CLOSURE_LIBS[@]}"; do
          local target
          target=$(basename "$lib_path")
          _copy_lib_safe "$lib_path" "$LIBDIR/$target"
        done
        # Reset for next collection
        _ELF_CLOSURE_LIBS=()
      }

      # Helper: safe copy with collision detection (#7)
      _copy_lib_safe() {
        local src="$1" dst="$2"
        local dst_name
        dst_name=$(basename "$dst")
        if [ -e "$dst" ] || [ -L "$dst" ]; then
          # Already exists — check for collision
          if [ -f "$dst" ] && [ -f "$src" ] && ! cmp -s "$(readlink -f "$src")" "$(readlink -f "$dst")"; then
            echo "  WARN: library collision for $dst_name, keeping first copy" >&2
            echo "    Existing: $(readlink -f "$dst")" >&2
            echo "    Skipping: $src" >&2
          fi
          # Same content or collision — keep existing (first-wins)
          return 0
        fi

        # Preserve symlink chains (#8): copy the real file first, then the symlink
        if [ -L "$src" ]; then
          local link_target real_file target_basename dst_dir
          link_target=$(readlink "$src")
          real_file=$(readlink -f "$src")
          target_basename=$(basename "$link_target")
          dst_dir=$(dirname "$dst")
          _copy_lib_safe "$real_file" "$dst_dir/$target_basename"
          ln -sf "$target_basename" "$dst"
          _record_bundled_lib_source "$dst_name" "$src"
        else
          cp "$src" "$dst"
          _record_bundled_lib_source "$dst_name" "$src"
        fi
      }

      # --- scrub_elf_nix_refs ---
      # Recursively fix RPATH, replace absolute DT_NEEDED entries, and
      # remove all /nix/store references from .so files under a directory.
      scrub_elf_nix_refs() {
        local target_dir="$1"
        while IFS= read -r -d "" lib_file; do
          chmod u+w "$lib_file"
          patchelf --set-rpath '${bundlePath}:${systemLibDir}' "$lib_file" 2>/dev/null || true
          local abs_needed
          abs_needed=$(patchelf --print-needed "$lib_file" 2>/dev/null | grep '^/' || true)
          for abs_lib in $abs_needed; do
            local soname
            soname=$(basename "$abs_lib")
            echo "  FIX: $lib_file: replacing DT_NEEDED $abs_lib -> $soname"
            patchelf --replace-needed "$abs_lib" "$soname" "$lib_file" 2>/dev/null || true
          done
          remove-references-to -t ${pkgs.stdenv.cc} "$lib_file" 2>/dev/null || true
          for ref in $(strings "$lib_file" | grep -o '/nix/store/[a-z0-9]\{32\}-[^/]*' | sort -u); do
            remove-references-to -t "$ref" "$lib_file" 2>/dev/null || true
          done
        done < <(find "$target_dir" -name '*.so*' -type f ! -type l -print0)
      }

      # --- copy_private_libs (#7, #8) ---
      # Copies closure libs into $LIBDIR.
      # - Collision detection: fails if same basename with different content (#7)
      # - Preserves symlink chains from source dirs (#8)
      copy_private_libs() {
        echo "==> Copying private libraries to $LIBDIR..."

        # Collect closure for main binary
        collect_elf_closure "$RESOLVED_BINARY"
        copy_closure_libs

        # Collect from extra lib packages
        ${builtins.concatStringsSep "\n" (
          map (pkg: ''
            _register_pkg_root "${pkg}"
            for so in "${pkg}"/lib/*.so*; do
              if [ -f "$so" ] && ! [ -L "$so" ]; then
                collect_elf_closure "$so"
                copy_closure_libs
              fi
            done
          '') extraLibPackages
        )}

        # Copy extra lib files directly
        ${builtins.concatStringsSep "\n" (
          map (extraLib: ''
            _register_pkg_root "${extraLib}"
            if [ -f "${extraLib}" ] || [ -L "${extraLib}" ]; then
              local target
              target=$(basename "${extraLib}")
              _copy_lib_safe "${extraLib}" "$LIBDIR/$target"
            fi
          '') extraLibs
        )}

        # Copy .so files and symlinks from extra packages
        ${builtins.concatStringsSep "\n" (
          map (pkg: ''
            _register_pkg_root "${pkg}"
            for so in "${pkg}"/lib/*.so*; do
              if [ -f "$so" ] || [ -L "$so" ]; then
                local target
                target=$(basename "$so")
                _copy_lib_safe "$so" "$LIBDIR/$target"
              fi
            done
          '') extraLibPackages
        )}

        ${lib.optionalString createCompatSymlinks ''
          # Create soname compat symlinks (opt-in)
          for lib_file in "$LIBDIR"/*.so.*; do
            [ ! -e "$lib_file" ] && continue
            local base soname
            base=$(basename "$lib_file")
            soname=$(echo "$base" | sed 's/\.so\..*/\.so/')
            if [ ! -e "$LIBDIR/$soname" ]; then
              ln -sf "$base" "$LIBDIR/$soname"
              _record_bundled_lib_alias "$soname" "$base"
            fi
          done
        ''}

        # Fix permissions, RPATH, absolute DT_NEEDED entries, and scrub nix store refs
        scrub_elf_nix_refs "$LIBDIR"

        echo "==> Library bundling complete."
      }

      # --- install_binary ---
      install_binary() {
        echo "==> Installing binary..."
        cp "$RESOLVED_BINARY" "$PKG/usr/bin/.${binName}-bin"
        chmod u+w,+x "$PKG/usr/bin/.${binName}-bin"
        patchelf --set-interpreter '${interpreter}' "$PKG/usr/bin/.${binName}-bin"
        patchelf --set-rpath '${bundlePath}:${systemLibDir}' "$PKG/usr/bin/.${binName}-bin"
        # Replace absolute-path DT_NEEDED entries with sonames
        local abs_needed
        abs_needed=$(patchelf --print-needed "$PKG/usr/bin/.${binName}-bin" 2>/dev/null | grep '^/' || true)
        for abs_lib in $abs_needed; do
          local soname
          soname=$(basename "$abs_lib")
          echo "  FIX: replacing DT_NEEDED $abs_lib -> $soname"
          patchelf --replace-needed "$abs_lib" "$soname" "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        done
        # Record the Qt major used by the main binary so the wrapper can
        # select a single plugin tree and avoid mixing Qt 5/6 plugins.
        if patchelf --print-needed "$PKG/usr/bin/.${binName}-bin" 2>/dev/null | grep -q '^libQt6Core\.so'; then
          echo 6 > "$LIBDIR/.qt-major"
        elif patchelf --print-needed "$PKG/usr/bin/.${binName}-bin" 2>/dev/null | grep -q '^libQt5Core\.so'; then
          echo 5 > "$LIBDIR/.qt-major"
        fi

        # Strip all nix store references from the binary
        remove-references-to -t ${pkgs.stdenv.cc} "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        remove-references-to -t ${package} "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        # Scrub any remaining /nix/store references
        for ref in $(strings "$PKG/usr/bin/.${binName}-bin" | grep -o '/nix/store/[a-z0-9]\{32\}-[^/]*' | sort -u); do
          remove-references-to -t "$ref" "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        done
        echo "==> Binary installed."
      }
    '';

  # --- install_control_file ---
  # Separate function since it needs the pre-rendered control template
  mkControlInstallCode =
    { controlFileTemplate }:
    ''
            install_control_file() {
              echo "==> Writing DEBIAN control files..."
              local installed_size
              installed_size=$(du -sk "$PKG/usr" | awk '{print $1}')
              cat > "$PKG/DEBIAN/control" <<'CONTROL_TEMPLATE_EOF'
      ${controlFileTemplate}
      CONTROL_TEMPLATE_EOF
              sed -i "s/@@INSTALLED_SIZE@@/$installed_size/" "$PKG/DEBIAN/control"
              if grep -q '@@NIX_TO_DEB_DEPENDS@@' "$PKG/DEBIAN/control"; then
                if [ -z "$COMPUTED_GLIBC_FLOOR" ]; then
                  echo "ERROR: GLIBC floor was not computed before control file generation" >&2
                  exit 1
                fi
                sed -i "s#@@NIX_TO_DEB_DEPENDS@@#libc6 (>= $COMPUTED_GLIBC_FLOOR)#" "$PKG/DEBIAN/control"
              fi
              echo "==> Control file written."
            }
    '';

  # Generate the share-copying and fixup code
  mkShareCode =
    {
      package,
      binName,
      shareFiles ? [ ],
      extraShareCopies ? [ ],
      fixDesktopFiles ? true,
      fixDbusServices ? true,
      fixSystemdServices ? true,
    }:
    ''
      copy_share_tree() {
        echo "==> Copying share files..."
        ${builtins.concatStringsSep "\n" (
          map (dir: ''
            if [ -d "${package}/share/${dir}" ]; then
              mkdir -p "$SHAREDIR/${dir}"
              cp -rL "${package}/share/${dir}/." "$SHAREDIR/${dir}/"
              chmod -R u+w "$SHAREDIR/${dir}"
            fi
          '') shareFiles
        )}

        # Extra share copies
        ${builtins.concatStringsSep "\n" (
          map (copy: ''
            if [ -e "${copy.src}" ]; then
              mkdir -p "$SHAREDIR/${copy.dst}"
              cp -rL "${copy.src}/." "$SHAREDIR/${copy.dst}/"
              chmod -R u+w "$SHAREDIR/${copy.dst}"
            fi
          '') extraShareCopies
        )}

        # Fix nix store paths in data files
        ${lib.optionalString fixDesktopFiles ''
          for f in "$SHAREDIR"/applications/*.desktop; do
            [ -f "$f" ] || continue
            sed -i 's|/nix/store/[^/]*/bin/|/usr/bin/|g' "$f"
            sed -i 's|/nix/store/[^/]*/share/|/usr/share/|g' "$f"
          done
        ''}
        ${lib.optionalString fixDbusServices ''
          for f in "$SHAREDIR"/dbus-1/services/*.service; do
            [ -f "$f" ] || continue
            sed -i 's|/nix/store/[^/]*/bin/|/usr/bin/|g' "$f"
            sed -i 's|/nix/store/[^/]*/share/|/usr/share/|g' "$f"
          done
        ''}
        ${lib.optionalString fixSystemdServices ''
          for f in "$SHAREDIR"/systemd/user/*.service; do
            [ -f "$f" ] || continue
            sed -i 's|/nix/store/[^/]*/bin/|/usr/bin/|g' "$f"
            sed -i 's|/nix/store/[^/]*/lib/|/usr/lib/|g' "$f"
            sed -i 's|/nix/store/[^/]*/share/|/usr/share/|g' "$f"
          done
        ''}

        # Strip remaining nix store references from data files
        find "$SHAREDIR" -type f \( -name "*.desktop" -o -name "*.service" -o -name "*.xml" \) -print0 2>/dev/null | \
          while IFS= read -r -d "" data_file; do
            remove-references-to -t ${pkgs.stdenv.cc} "$data_file" 2>/dev/null || true
            remove-references-to -t ${package} "$data_file" 2>/dev/null || true
          done || true

        echo "==> Share files copied."
      }
    '';

  # --- verify_package_tree (#6) ---
  mkVerifyCode =
    {
      pname,
      bundlePath,
      allowedSystemLibs ? [ ],
    }:
    ''
      verify_package_tree() {
        echo "==> Verifying package tree for /nix/store references..."
        local violations=0
        local manifest_path="$PKG/usr/share/doc/${pname}/build-manifest.json"

        # Scan all staged files for /nix/store references
        while IFS= read -r -d "" staged_file; do
          # Skip the build manifest itself
          [ "$staged_file" = "$manifest_path" ] && continue

          # Check if it's an ELF file
          if file -b "$staged_file" | grep -q "ELF"; then
            # Use strings to check for nix store refs in ELF
            # Exclude scrubbed references (eeee... hashes from remove-references-to)
            local real_refs
            real_refs=$(strings "$staged_file" | grep '/nix/store' | grep -v '/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' || true)
            if [ -n "$real_refs" ]; then
              echo "  VIOLATION (ELF): $staged_file contains /nix/store references" >&2
              echo "$real_refs" | head -5 | sed 's/^/    /' >&2
              violations=$((violations + 1))
            fi
          else
            # Text file — use grep, excluding scrubbed references
            local real_refs
            real_refs=$(grep '/nix/store' "$staged_file" 2>/dev/null | grep -v '/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' || true)
            if [ -n "$real_refs" ]; then
              echo "  VIOLATION (text): $staged_file contains /nix/store references" >&2
              echo "$real_refs" | head -5 | sed 's/^/    /' >&2
              violations=$((violations + 1))
            fi
          fi
        done < <(find "$PKG" -type f -print0)

        # Check staged ELF files' DT_NEEDED are resolvable
        local unresolved=0
        while IFS= read -r -d "" staged_file; do
          if file -b "$staged_file" | grep -q "ELF"; then
            local needed
            needed=$(patchelf --print-needed "$staged_file" 2>/dev/null) || continue
            for lib_name in $needed; do
              # Absolute paths in DT_NEEDED are always a bug at this stage
              if [[ "$lib_name" == /* ]]; then
                echo "  ABSOLUTE DT_NEEDED: $staged_file needs $lib_name (should be soname only)" >&2
                unresolved=$((unresolved + 1))
                continue
              fi
              local found=false
              # Check in bundled LIBDIR
              [ -f "$LIBDIR/$lib_name" ] && found=true
              # Check system lib dir
              [ "$found" = false ] && {
                for allowed in ${
                  builtins.concatStringsSep " " (map (l: ''"${l}"'') allowedSystemLibs)
                }; do
                  case "$lib_name" in
                    "$allowed"*) found=true; break ;;
                  esac
                done
              }
              if [ "$found" = false ]; then
                echo "  UNRESOLVED: $staged_file needs $lib_name" >&2
                unresolved=$((unresolved + 1))
              fi
            done
          fi
        done < <(find "$PKG" -type f -print0)

        if [ $violations -gt 0 ]; then
          echo "ERROR: Found $violations file(s) with /nix/store references!" >&2
          echo "The .deb would not work on a non-NixOS system." >&2
          exit 1
        fi

        if [ $unresolved -gt 0 ]; then
          echo "ERROR: $unresolved unresolved DT_NEEDED entries found." >&2
          echo "These libraries are not bundled and not in allowedSystemLibs." >&2
          echo "The .deb would fail at runtime on the target system." >&2
          echo "To allow specific system-provided libs, add them to allowedSystemLibs." >&2
          exit 1
        fi

        echo "==> Verification passed: no /nix/store leaks detected."
      }
    '';

  # --- write_build_manifest ---
  mkManifestCode =
    {
      pname,
      version,
      debArch,
    }:
    ''
      write_build_manifest() {
        echo "==> Writing build manifest..."
        local manifest_dir="$PKG/usr/share/doc/${pname}"
        local manifest_path="$manifest_dir/build-manifest.json"
        local bundled_libs_json="{}"
        mkdir -p "$manifest_dir"

        if [ ''${#_BUNDLED_LIB_SOURCES[@]} -gt 0 ]; then
          bundled_libs_json=$(
            while IFS= read -r bundled_name; do
              jq -cn \
                --arg key "$bundled_name" \
                --arg value "''${_BUNDLED_LIB_SOURCES[$bundled_name]}" \
                '{ key: $key, value: $value }'
            done < <(printf '%s\n' "''${!_BUNDLED_LIB_SOURCES[@]}" | LC_ALL=C sort) | jq -s 'from_entries'
          )
        fi

        jq -n \
          --arg pname "${pname}" \
          --arg version "${version}" \
          --arg arch "${debArch}" \
          --arg binary "$RESOLVED_BINARY" \
          --arg glibc_floor "$COMPUTED_GLIBC_FLOOR" \
          --argjson libs "$bundled_libs_json" \
          '{
            pname: $pname,
            version: $version,
            architecture: $arch,
            resolved_binary: $binary,
            bundled_libs: $libs,
            glibc_floor: (if $glibc_floor == "" then null else $glibc_floor end),
            built_by: "nix-to-deb"
          }' > "$manifest_path"

        jq -e '
          (.bundled_libs | type) == "object"
          and ([.bundled_libs[]? | (type == "string")] | index(false) == null)
          and (.glibc_floor == null or (.glibc_floor | type) == "string")
        ' "$manifest_path" >/dev/null

        echo "==> Build manifest written."
      }
    '';

}
