# Shell function library for nix-to-deb build phase
#
# Exports mkShellHelpers — takes resolved config, returns a bash string
# defining all shell functions used in the installPhase pipeline.
#
# Fixes:
#   #1 — resolve_binary: consistent binary resolution
#   #2 — collect_elf_closure: empty excludeLibs no longer drops all libs
#   #3 — collect_elf_closure: patchelf-based instead of ldd scraping
#   #6 — verify_package_tree: detects leftover /nix/store references
#   #7 — copy_private_libs: collision detection
#   #8 — copy_private_libs: preserves symlink chains
{ lib, pkgs }:

{
  mkShellHelpers =
    {
      pname,
      binName,
      package,
      realBinary ? null,
      bundlePath,
      systemLibDir,
      interpreter,
      excludeLibs ? [ "glibc" ],
      extraLibs ? [ ],
      extraLibPackages ? [ ],
      createCompatSymlinks ? false,
      allowedSystemLibs ? [
        "libm.so"
        "libc.so"
        "libdl.so"
        "librt.so"
        "libpthread.so"
        "libutil.so"
        "libcrypt.so"
        "libresolv.so"
        "libnss_dns.so"
        "libnss_files.so"
        "libgcc_s.so"
        "libstdc++.so"
        "ld-linux-x86-64.so"
        "ld-linux-aarch64.so"
        "linux-vdso.so"
      ],
    }:
    let
      excludePattern =
        if excludeLibs == [ ] then "" else builtins.concatStringsSep "\\|" excludeLibs;

      hasExcludes = excludeLibs != [ ];
    in
    ''
      # ==============================================================
      # Shell helpers generated by nix-to-deb
      # ==============================================================

      # Global state
      RESOLVED_BINARY=""
      declare -A _ELF_CLOSURE_VISITED
      declare -a _ELF_CLOSURE_LIBS

      # --- resolve_binary (#1) ---
      # Determines the real binary path. If realBinary was specified, uses it.
      # Otherwise checks .${binName}-wrapped first, then ${binName}.
      # Fails early if the binary doesn't exist.
      resolve_binary() {
        ${if realBinary != null then ''
        if [ -f "${realBinary}" ]; then
          RESOLVED_BINARY="${realBinary}"
        else
          echo "ERROR: specified realBinary '${realBinary}' does not exist" >&2
          exit 1
        fi
        '' else ''
        if [ -f "${package}/bin/.${binName}-wrapped" ]; then
          RESOLVED_BINARY="${package}/bin/.${binName}-wrapped"
        elif [ -f "${package}/bin/${binName}" ]; then
          RESOLVED_BINARY="${package}/bin/${binName}"
        else
          echo "ERROR: could not find binary '${binName}' in ${package}/bin/" >&2
          echo "  Tried: .${binName}-wrapped, ${binName}" >&2
          exit 1
        fi
        ''}
        echo "==> Resolved binary: $RESOLVED_BINARY"
      }

      # --- collect_elf_closure (#3, #2) ---
      # Deterministic ELF closure walker using patchelf instead of ldd.
      # Resolves DT_NEEDED entries against RPATH dirs.
      # When excludeLibs is empty, no filtering is applied (#2).
      collect_elf_closure() {
        local root_file="$1"
        _ELF_CLOSURE_VISITED=()
        _ELF_CLOSURE_LIBS=()
        _walk_elf_deps "$root_file"
      }

      _walk_elf_deps() {
        local file="$1"
        local real_file

        # Resolve symlinks to canonical path
        real_file=$(readlink -f "$file" 2>/dev/null) || real_file="$file"

        # Skip if already visited
        [ -n "''${_ELF_CLOSURE_VISITED[$real_file]+x}" ] && return
        _ELF_CLOSURE_VISITED["$real_file"]=1

        # Get DT_NEEDED entries
        local needed
        needed=$(patchelf --print-needed "$real_file" 2>/dev/null) || return 0

        # Get RPATH search dirs
        local rpath
        rpath=$(patchelf --print-rpath "$real_file" 2>/dev/null) || rpath=""

        # Build array of search dirs from RPATH
        local -a search_dirs
        IFS=':' read -ra search_dirs <<< "$rpath"

        for lib_name in $needed; do
          local found=""

          # Handle absolute-path DT_NEEDED entries (nix often uses these)
          if [[ "$lib_name" == /* ]]; then
            if [ -f "$lib_name" ]; then
              found="$lib_name"
            else
              echo "  NOTE: absolute DT_NEEDED path does not exist: $lib_name (from $real_file)" >&2
              continue
            fi
          fi

          # Search in RPATH dirs (only for soname-style entries)
          if [ -z "$found" ]; then
            for dir in "''${search_dirs[@]}"; do
              # Expand $ORIGIN if present
              local expanded_dir
              expanded_dir="''${dir/\$ORIGIN/$(dirname "$real_file")}"
              if [ -f "$expanded_dir/$lib_name" ]; then
                found="$expanded_dir/$lib_name"
                break
              fi
            done
          fi

          # Not found in RPATH — check if it's an allowed system lib
          if [ -z "$found" ]; then
            local is_allowed=false
            for allowed in ${builtins.concatStringsSep " " (map (l: ''"${l}"'') allowedSystemLibs)}; do
              case "$lib_name" in
                "$allowed"*) is_allowed=true; break ;;
              esac
            done
            if $is_allowed; then
              continue
            fi
            # Not allowed and not found — note it and move on
            echo "  NOTE: unresolved DT_NEEDED: $lib_name (from $real_file)" >&2
            continue
          fi

          # Apply exclude filter only if we have excludes (#2)
          ${
            if hasExcludes then
              ''
                if echo "$found" | grep -q '${excludePattern}'; then
                  continue
                fi
              ''
            else
              "# No excludeLibs — bundling all resolved libs"
          }

          # Skip if not from nix store
          case "$found" in
            /nix/store/*) ;;
            *) continue ;;
          esac

          _ELF_CLOSURE_LIBS+=("$found")
          # Recurse into this lib's deps
          _walk_elf_deps "$found"
        done
      }

      # Helper: copy closure libs accumulated in _ELF_CLOSURE_LIBS
      copy_closure_libs() {
        for lib_path in "''${_ELF_CLOSURE_LIBS[@]}"; do
          local target
          target=$(basename "$lib_path")
          _copy_lib_safe "$lib_path" "$LIBDIR/$target"
        done
        # Reset for next collection
        _ELF_CLOSURE_LIBS=()
      }

      # Helper: safe copy with collision detection (#7)
      _copy_lib_safe() {
        local src="$1" dst="$2"
        if [ -e "$dst" ] || [ -L "$dst" ]; then
          # Already exists — check for collision
          if [ -f "$dst" ] && [ -f "$src" ] && ! cmp -s "$(readlink -f "$src")" "$(readlink -f "$dst")"; then
            echo "  WARN: library collision for $(basename "$dst"), keeping first copy" >&2
            echo "    Existing: $(readlink -f "$dst")" >&2
            echo "    Skipping: $src" >&2
          fi
          # Same content or collision — keep existing (first-wins)
          return 0
        fi

        # Preserve symlink chains (#8): copy the real file first, then the symlink
        if [ -L "$src" ]; then
          local link_target real_file
          link_target=$(readlink "$src")
          real_file=$(readlink -f "$src")
          local target_basename
          target_basename=$(basename "$link_target")
          local dst_dir
          dst_dir=$(dirname "$dst")
          # Copy the real file if not already present
          if [ ! -e "$dst_dir/$target_basename" ]; then
            cp "$real_file" "$dst_dir/$target_basename"
          fi
          # Create the symlink
          ln -sf "$target_basename" "$dst"
        else
          cp "$src" "$dst"
        fi
      }

      # --- copy_private_libs (#7, #8) ---
      # Copies closure libs into $LIBDIR.
      # - Collision detection: fails if same basename with different content (#7)
      # - Preserves symlink chains from source dirs (#8)
      copy_private_libs() {
        echo "==> Copying private libraries to $LIBDIR..."

        # Collect closure for main binary
        collect_elf_closure "$RESOLVED_BINARY"
        copy_closure_libs

        # Collect from extra lib packages
        ${builtins.concatStringsSep "\n" (map (pkg: ''
          for so in "${pkg}"/lib/*.so*; do
            if [ -f "$so" ] && ! [ -L "$so" ]; then
              collect_elf_closure "$so"
              copy_closure_libs
            fi
          done
        '') extraLibPackages)}

        # Copy extra lib files directly
        ${builtins.concatStringsSep "\n" (map (extraLib: ''
          if [ -f "${extraLib}" ]; then
            local target
            target=$(basename "${extraLib}")
            _copy_lib_safe "${extraLib}" "$LIBDIR/$target"
          elif [ -L "${extraLib}" ]; then
            local linkto target
            linkto=$(basename "$(readlink "${extraLib}")")
            target=$(basename "${extraLib}")
            [ "$linkto" != "$target" ] && [ ! -e "$LIBDIR/$target" ] && \
              ln -sf "$linkto" "$LIBDIR/$target"
          fi
        '') extraLibs)}

        # Copy .so files and symlinks from extra packages
        ${builtins.concatStringsSep "\n" (map (pkg: ''
          for so in "${pkg}"/lib/*.so*; do
            if [ -f "$so" ] && ! [ -L "$so" ]; then
              local target
              target=$(basename "$so")
              _copy_lib_safe "$so" "$LIBDIR/$target"
            elif [ -L "$so" ]; then
              local linkto target
              linkto=$(basename "$(readlink "$so")")
              target=$(basename "$so")
              [ "$linkto" != "$target" ] && [ ! -e "$LIBDIR/$target" ] && \
                ln -sf "$linkto" "$LIBDIR/$target"
            fi
          done
        '') extraLibPackages)}

        ${lib.optionalString createCompatSymlinks ''
          # Create soname compat symlinks (opt-in)
          for lib_file in "$LIBDIR"/*.so.*; do
            [ ! -e "$lib_file" ] && continue
            local base soname
            base=$(basename "$lib_file")
            soname=$(echo "$base" | sed 's/\.so\..*/\.so/')
            [ ! -e "$LIBDIR/$soname" ] && ln -sf "$base" "$LIBDIR/$soname"
          done
        ''}

        # Fix permissions, RPATH, absolute DT_NEEDED entries, and scrub nix store refs
        for lib_file in "$LIBDIR"/*.so*; do
          if [ -f "$lib_file" ] && ! [ -L "$lib_file" ]; then
            chmod u+w "$lib_file"
            patchelf --set-rpath '${bundlePath}:${systemLibDir}' "$lib_file" 2>/dev/null || true
            # Replace absolute-path DT_NEEDED entries with sonames
            local abs_needed
            abs_needed=$(patchelf --print-needed "$lib_file" 2>/dev/null | grep '^/' || true)
            for abs_lib in $abs_needed; do
              local soname
              soname=$(basename "$abs_lib")
              echo "  FIX: $lib_file: replacing DT_NEEDED $abs_lib -> $soname"
              patchelf --replace-needed "$abs_lib" "$soname" "$lib_file" 2>/dev/null || true
            done
            remove-references-to -t ${pkgs.stdenv.cc} "$lib_file" 2>/dev/null || true
            for ref in $(strings "$lib_file" | grep -o '/nix/store/[a-z0-9]\{32\}-[^/]*' | sort -u); do
              remove-references-to -t "$ref" "$lib_file" 2>/dev/null || true
            done
          fi
        done

        echo "==> Library bundling complete."
      }

      # --- install_binary ---
      install_binary() {
        echo "==> Installing binary..."
        cp "$RESOLVED_BINARY" "$PKG/usr/bin/.${binName}-bin"
        chmod u+w,+x "$PKG/usr/bin/.${binName}-bin"
        patchelf --set-interpreter '${interpreter}' "$PKG/usr/bin/.${binName}-bin"
        patchelf --set-rpath '${bundlePath}:${systemLibDir}' "$PKG/usr/bin/.${binName}-bin"
        # Replace absolute-path DT_NEEDED entries with sonames
        local abs_needed
        abs_needed=$(patchelf --print-needed "$PKG/usr/bin/.${binName}-bin" 2>/dev/null | grep '^/' || true)
        for abs_lib in $abs_needed; do
          local soname
          soname=$(basename "$abs_lib")
          echo "  FIX: replacing DT_NEEDED $abs_lib -> $soname"
          patchelf --replace-needed "$abs_lib" "$soname" "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        done
        # Strip all nix store references from the binary
        remove-references-to -t ${pkgs.stdenv.cc} "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        remove-references-to -t ${package} "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        # Scrub any remaining /nix/store references
        for ref in $(strings "$PKG/usr/bin/.${binName}-bin" | grep -o '/nix/store/[a-z0-9]\{32\}-[^/]*' | sort -u); do
          remove-references-to -t "$ref" "$PKG/usr/bin/.${binName}-bin" 2>/dev/null || true
        done
        echo "==> Binary installed."
      }
    '';

  # --- install_control_file ---
  # Separate function since it needs the pre-rendered control template
  mkControlInstallCode =
    { controlFileTemplate }:
    ''
      install_control_file() {
        echo "==> Writing DEBIAN control files..."
        local installed_size
        installed_size=$(du -sk "$PKG" | awk '{print $1}')
        cat > "$PKG/DEBIAN/control" <<'CONTROL_TEMPLATE_EOF'
${controlFileTemplate}
CONTROL_TEMPLATE_EOF
        sed -i "s/@@INSTALLED_SIZE@@/$installed_size/" "$PKG/DEBIAN/control"
        echo "==> Control file written."
      }
    '';

  # Generate the share-copying and fixup code
  mkShareCode =
    {
      package,
      binName,
      shareFiles ? [ ],
      extraShareCopies ? [ ],
      fixDesktopFiles ? true,
      fixDbusServices ? true,
      fixSystemdServices ? true,
    }:
    ''
      copy_share_tree() {
        echo "==> Copying share files..."
        ${builtins.concatStringsSep "\n" (map (dir: ''
          if [ -d "${package}/share/${dir}" ]; then
            mkdir -p "$SHAREDIR/${dir}"
            cp -rL "${package}/share/${dir}/." "$SHAREDIR/${dir}/"
            chmod -R u+w "$SHAREDIR/${dir}"
          fi
        '') shareFiles)}

        # Extra share copies
        ${builtins.concatStringsSep "\n" (map (copy: ''
          if [ -e "${copy.src}" ]; then
            mkdir -p "$SHAREDIR/${copy.dst}"
            cp -rL "${copy.src}/." "$SHAREDIR/${copy.dst}/"
            chmod -R u+w "$SHAREDIR/${copy.dst}"
          fi
        '') extraShareCopies)}

        # Fix nix store paths in data files
        ${lib.optionalString fixDesktopFiles ''
          for f in "$SHAREDIR"/applications/*.desktop; do
            [ -f "$f" ] && sed -i 's|/nix/store/[^/]*/bin/${binName}|/usr/bin/${binName}|g' "$f"
          done
        ''}
        ${lib.optionalString fixDbusServices ''
          for f in "$SHAREDIR"/dbus-1/services/*.service; do
            [ -f "$f" ] && sed -i 's|/nix/store/[^/]*/bin/${binName}|/usr/bin/${binName}|g' "$f"
          done
        ''}
        ${lib.optionalString fixSystemdServices ''
          for f in "$SHAREDIR"/systemd/user/*.service; do
            [ -f "$f" ] && sed -i 's|/nix/store/[^/]*|/usr|g' "$f"
          done
        ''}

        # Strip remaining nix store references from data files
        find "$SHAREDIR" -type f \( -name "*.desktop" -o -name "*.service" -o -name "*.xml" \) \
          -exec remove-references-to -t ${pkgs.stdenv.cc} '{}' + 2>/dev/null || true

        echo "==> Share files copied."
      }
    '';

  # --- verify_package_tree (#6) ---
  mkVerifyCode =
    {
      pname,
      bundlePath,
      allowedSystemLibs ? [ ],
    }:
    ''
      verify_package_tree() {
        echo "==> Verifying package tree for /nix/store references..."
        local violations=0
        local manifest_path="$PKG/usr/share/doc/${pname}/build-manifest.json"

        # Scan all staged files for /nix/store references
        while IFS= read -r -d "" staged_file; do
          # Skip the build manifest itself
          [ "$staged_file" = "$manifest_path" ] && continue

          # Check if it's an ELF file
          if file -b "$staged_file" | grep -q "ELF"; then
            # Use strings to check for nix store refs in ELF
            # Exclude scrubbed references (eeee... hashes from remove-references-to)
            local real_refs
            real_refs=$(strings "$staged_file" | grep '/nix/store' | grep -v '/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' || true)
            if [ -n "$real_refs" ]; then
              echo "  VIOLATION (ELF): $staged_file contains /nix/store references" >&2
              echo "$real_refs" | head -5 | sed 's/^/    /' >&2
              violations=$((violations + 1))
            fi
          else
            # Text file — use grep, excluding scrubbed references
            local real_refs
            real_refs=$(grep '/nix/store' "$staged_file" 2>/dev/null | grep -v '/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' || true)
            if [ -n "$real_refs" ]; then
              echo "  VIOLATION (text): $staged_file contains /nix/store references" >&2
              echo "$real_refs" | head -5 | sed 's/^/    /' >&2
              violations=$((violations + 1))
            fi
          fi
        done < <(find "$PKG" -type f -print0)

        # Check staged ELF files' DT_NEEDED are resolvable
        local unresolved=0
        while IFS= read -r -d "" staged_file; do
          if file -b "$staged_file" | grep -q "ELF"; then
            local needed
            needed=$(patchelf --print-needed "$staged_file" 2>/dev/null) || continue
            for lib_name in $needed; do
              # Absolute paths in DT_NEEDED are always a bug at this stage
              if [[ "$lib_name" == /* ]]; then
                echo "  ABSOLUTE DT_NEEDED: $staged_file needs $lib_name (should be soname only)" >&2
                unresolved=$((unresolved + 1))
                continue
              fi
              local found=false
              # Check in bundled LIBDIR
              [ -f "$LIBDIR/$lib_name" ] && found=true
              # Check system lib dir
              [ "$found" = false ] && {
                for allowed in ${builtins.concatStringsSep " " (map (l: ''"${l}"'') allowedSystemLibs)}; do
                  case "$lib_name" in
                    "$allowed"*) found=true; break ;;
                  esac
                done
              }
              if [ "$found" = false ]; then
                echo "  UNRESOLVED: $staged_file needs $lib_name" >&2
                unresolved=$((unresolved + 1))
              fi
            done
          fi
        done < <(find "$PKG" -type f -print0)

        if [ $violations -gt 0 ]; then
          echo "ERROR: Found $violations file(s) with /nix/store references!" >&2
          echo "The .deb would not work on a non-NixOS system." >&2
          exit 1
        fi

        if [ $unresolved -gt 0 ]; then
          echo "ERROR: $unresolved unresolved DT_NEEDED entries found." >&2
          echo "These libraries are not bundled and not in allowedSystemLibs." >&2
          echo "The .deb would fail at runtime on the target system." >&2
          echo "To allow specific system-provided libs, add them to allowedSystemLibs." >&2
          exit 1
        fi

        echo "==> Verification passed: no /nix/store leaks detected."
      }
    '';

  # --- write_build_manifest ---
  mkManifestCode =
    { pname, version, debArch }:
    ''
      write_build_manifest() {
        echo "==> Writing build manifest..."
        local manifest_dir="$PKG/usr/share/doc/${pname}"
        mkdir -p "$manifest_dir"

        local bundled_libs
        bundled_libs=$(cd "$LIBDIR" 2>/dev/null && ls *.so* 2>/dev/null | jq -R -s 'split("\n") | map(select(. != ""))') || bundled_libs="[]"

        jq -n \
          --arg pname "${pname}" \
          --arg version "${version}" \
          --arg arch "${debArch}" \
          --arg binary "$RESOLVED_BINARY" \
          --argjson libs "$bundled_libs" \
          '{
            pname: $pname,
            version: $version,
            architecture: $arch,
            resolved_binary: $binary,
            bundled_libs: $libs,
            built_by: "nix-to-deb"
          }' > "$manifest_dir/build-manifest.json"

        echo "==> Build manifest written."
      }
    '';
}
